# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
# group department by salarys
salary = df.groupby('Department')['Salary'].mean()  # This means we used here is called 'Aggregation'.
salary
# department wise employee count
empl = df.groupby("Department")['Employee'].count()
empl
# Aggregation
salary = df.groupby('Department')['Salary'].agg(['mean','max','min','count'])  # This means we used here is called 'Aggregation'.
salary

                    mean    max    min  count
Department
Finance     61000.000000  65000  58000      3
HR          51000.000000  52000  50000      2
IT          72333.333333  75000  70000      3

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
df
result = df.groupby('Department').agg(  # for making multiple columns, use dict inside dict
    {
        'Salary' :['mean', 'max', 'min'],
        'Employee' :['count'],
        'Age' :['max','mean']
    }
)
result

                  Salary               Employee Age
                    mean    max    min    count max       mean
Department
Finance     61000.000000  65000  58000        3  35  29.333333
HR          51000.000000  52000  50000        2  29  28.500000
IT          72333.333333  75000  70000        3  32  31.000000

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
pivot = df.pivot_table(values='Salary', index='Department', aggfunc="mean")
pivot

pivot = df.pivot_table(values=['Salary','Age'], index='Department', aggfunc=["sum","mean"])  # i don't know whether this two agg func works or not
pivot

# Crosstab -> No of employees by Department and Age group
# Dataframe -> new column AgeGroup column

#pd.cut() -> columns, bins(diff from one column to another one), label (an indicator), this pd.cut() does slicing
df['AgeGroup'] = pd.cut(df['Age'], bins = [25,30,35], labels=["25-30","31-35"])
result = pd.crosstab(df['Department'], df['AgeGroup'])
result

AgeGroup    25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:
import pandas as pd

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "George", "Hannah"],
    "Salary": [50000, 65000, 60000, 70000, 52000, 58000, 72000, 51000],
    "Age": [28, 35, 30, 40, 26, 32, 38, 27],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai", "Delhi", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.