# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

print(b,"\n\n")

# # Select rows where age is greater than 30
# c = b[b['Age']>30]

# # rows select where Score is less than 90
# d = b[b['Score'] < 90]


# # Using AND(&)
# e = b[(b['Age'] > 30) & (b['Score'] < 90)]


# # Using same cond change the operator (|)
# f = b[(b['Age'] > 30) | (b['Score'] < 90)]

# # we want score which is not greater than 85
# g = b[~(b['Score'] > 85)]  # Using NOT ~ operator

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
# Inclusive  (Cond must be in parentheses)
ab = b[(b['Age'] >= 20) & (b['Age'] <= 30)]
ab

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92
4   Emma   22     95

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
# Age should be greater than 20 using query()
# b.query("Age<20")

# Multiple Conditions - Age < 35 and Score >= 85
# b.query("Age < 35 and Score >= 85")

# Age >= 20 and Age <=30
# b.query("Age >=20 & Age <= 30")

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
# b['Name'].str.lower() # lower
# b['Name'].str.upper() # upper
# b['Age'].sum()


# Contains
# b[b['Name'].str.contains('a', case=False)]  # Checking whether 'a' comes in these word or not, and to avoid case sensitive cases we use 'case=False'

# # Startswith - > letter/ word starting with
# b[b['Name'].str.startswith('A')]


# #Endswith
# b[b['Name'].str.endswith('e')]

# Aise heee practice, dono ko combine karke
# b[(b['Name'].str.startswith('A')) & (b['Name'].str.endswith('e'))]

    Name  Age  Score
3  David   40     85

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:
import pandas as pd

# 1. Build a DataFrame with columns: Name, Age, City, Score
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank"],
    "Age": [24, 32, 28, 40, 22, 30],
    "City": ["Delhi", "Mumbai", "Pune", "Chennai", "Delhi", "Mumbai"],
    "Score": [90, 82, 88, 75, 95, 84]
}

df = pd.DataFrame(data)

# 2. Use boolean indexing to select rows where Age > 25
# Write your code here
# df['Age']>25

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here
print(df,"\n\n")
# df = df[(df['City'] == 'Delhi') | (df['City'] == 'Mumbai')]
# print(df)

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here
# df.query("Score >= 85 and Age < 35")

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

# df['City'] =  df['City'].str.lower()
# df['City'] = df['City'].str.replace('Delhi', 'New Delhi')
# print(df)

      Name  Age     City  Score
0    Alice   24    Delhi     90
1      Bob   32   Mumbai     82
2  Charlie   28     Pune     88
3    David   40  Chennai     75
4     Emma   22    Delhi     95
5    Frank   30   Mumbai     84


      Name  Age     City  Score
0    Alice   24    delhi     90
1      Bob   32   mumbai     82
2  Charlie   28     pune     88
3    David   40  chennai     75
4     Emma   22    delhi     95
5    Frank   30   mumbai     84

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.