# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [ ]:
import pandas as pd
import numpy as np
# New dataset
data = {
    "Product": ["Pen", "Notebook", "Pencil", "Marker", "Eraser", "Sharpener"],
    "Price": [10, 50, 5, 30, 8, 12],
    "Stock": [100, 60, 200, 80, 150, 120],
    "Rating": [4.5, 4.7, 4.4, 4.8, 4.4, 4.4]
}
df = pd.DataFrame(data)
df['Keyboard'] = [1,2,3,4,5,6]
print(df)
# df = pd.DataFrame(data)
# print("Real Dataframe\n",df,"\n\n")

# df.sort_values(by="Price")   # Sorts COLMUNS values # Gives in ascending order by default
# df.sort_values(by="Price", ascending=False)  # gives in descending order
# df.sort_values(by='Rating', ascending=False)

# # Multiple Condition
# df.sort_values(by=['Price', 'Stock'])
# df.sort_values(by=['Price', 'Stock'], ascending=[True, False])  # not much in use for now, but in future yeah
# # sorting happens on the first basis as here it's price
# # so the sorting happens in accordance with price

# # Sorting index
# df.sort_index(ascending=False)

"""# df.sort_values(by="Product")
# df.sort_values(by=['Product','Stock'],ascending=[False, True])
df.sort_index(ascending=False)"""

     Product  Price  Stock  Rating  Keyboard
0        Pen     10    100     4.5         1
1   Notebook     50     60     4.7         2
2     Pencil      5    200     4.4         3
3     Marker     30     80     4.8         4
4     Eraser      8    150     4.4         5
5  Sharpener     12    120     4.4         6

'# df.sort_values(by="Product")\n# df.sort_values(by=[\'Product\',\'Stock\'],ascending=[False, True])\ndf.sort_index(ascending=False)'

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [ ]:
# df['Price'].mean()
# df.mean(numeric_only=True) #numeric_only means in a dataframe you might have a string columns as well, so we need average of only numbers, so we use this
# df.median(numeric_only=True) # means numeric_only see sirf numbers ka he mean, median, mode hota h, naa ki strings ka...
# df.mode(numeric_only=True)
# df.std(numeric_only=True)
# df.describe()
"""
# df['Price'].mean()
# df.mean(numeric_only=True)
# df.mode(numeric_only=True)
# df.median(numeric_only=True)
# df.std(numeric_only=True)
# df.describe()"""

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.533333
std    17.486185   50.760877  0.175119
min     5.000000   60.000000  4.400000
25%     8.500000   85.000000  4.400000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [ ]:
import pandas as pd

# New dataset
data = {
    "Product": ["Pen", "Notebook", "Pen", "Marker", "Eraser", "Sharpener"],
    "Price": [10, 50, 5, 30, 8, 12],
    "Stock": [100, 60, 200, 80, 150, 120],
    "Rating": [4.5, 4.7, 4.4, 4.8, 4.4, 4.4]
}

df = pd.DataFrame(data)

print(df,"\n\n")

# df['Product'].value_counts()
# df['Product'].value_counts(normalize=True) # This normalize -> Gives answer in percentage, that's it

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2        Pen      5    200     4.4
3     Marker     30     80     4.8
4     Eraser      8    150     4.4
5  Sharpener     12    120     4.4

In [ ]:
# df['Product'].value_counts()
df['Product'].value_counts(normalize=True) # normalize ye batata ha ki dataset mai se ye wala part kitna portion lee rha hai uss poore dataset mai se...

# df['Rating'].value_counts()

Product
Pen          0.333333
Notebook     0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [ ]:
df

     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [ ]:
"""How to read the values
1 → move together perfectly
-1 → move opposite perfectly
0 → no clear relationship"""

# df.corr(numeric_only=True)  # do columns ka relation kaisa h, as like inversly proprtional type ka relation,
# df.cov(numeric_only=True)
# df['Price'].corr(df['Stock'])
# it shows that howe price and stock are connected together, if answer in -1, strongle opp, -0.5 = medium movement, and if around 0 - not much relationship
# df['Rating'].corr(df['Stock'])
"""
# df.corr(numeric_only=True)
# df.cov(numeric_only=True)
# df['Price'].corr(df['Rating'])"""

np.float64(-0.7799731888824404)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [ ]:
# Write your mini practice solution here
import pandas as pd
import numpy as np

# 1. Build a DataFrame with columns: Name, Age, Score, Height
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95],
    "Height": [160, 175, 168, 180, 158]
}

df = pd.DataFrame(data)
print('Real\n',df,'\n\n')
# 2. Sort the data by Score (descending)
# Write your code here

# df = df.sort_values(by='Score',ascending=False)
# print(df)

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here
# print("\n\nMean \n\n", df.mean( numeric_only=True), "\nMedian\n\n", df.median( numeric_only=True), '\nMode\n\n', df.mode( numeric_only=True), "\nStd\n\n", df.std( numeric_only=True))

# 4. Use value_counts on Name or any categorical column
# Write your code here
# df['Age'].value_counts(normalize=True)


# 5. Compute corr() and cov() for all numeric columns
# Write your code here

# df.corr(numeric_only=True)
# df.cov(numeric_only=True)

Real
       Name  Age  Score  Height
0    Alice   25     88     160
1      Bob   30     92     175
2  Charlie   35     79     168
3    David   40     85     180
4     Emma   22     95     158

          Age  Score  Height
Age     53.30 -32.65   59.90
Score  -32.65  38.70  -19.45
Height  59.90 -19.45   89.20

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.