# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)
print(df)

      Name  Math  Science
0    Alice    88       90
1      Bob    75       80
2  Charlie    92       78
3    David    60       70
4     Emma    85       95

In [ ]:
# Adding 5 Marks for every student
df['Math_Bonus'] = df['Math'].apply(lambda x:x+5)
print(df)

      Name  Math  Science  Math_Bonus  Average Grade  Math_Bonuu
0    Alice    88       90          93     89.0     B          93
1      Bob    75       80          80     77.5     B          80
2  Charlie    92       78          97     85.0     B          97
3    David    60       70          65     65.0     C          65
4     Emma    85       95          90     90.0     A          90

In [ ]:
# Taking Average from both rows
df['Average'] = df.apply(
    lambda row : (row['Math']+ row['Science'])/2,
    axis = 1
)
print(df)

      Name  Math  Science  Math_Bonus  Average
0    Alice    88       90          93     89.0
1      Bob    75       80          80     77.5
2  Charlie    92       78          97     85.0
3    David    60       70          65     65.0
4     Emma    85       95          90     90.0

In [ ]:
# Custome Func
def grade(row):
  avg = (row['Math']+ row['Science']) / 2

  if avg >= 90:
    return 'A'
  elif avg >= 75:
    return 'B'
  else:
    return 'C'
df['Grade'] = df.apply(grade, axis=1)
df

      Name  Math  Science  Math_Bonus  Average Grade
0    Alice    88       90          93     89.0     B
1      Bob    75       80          80     77.5     B
2  Charlie    92       78          97     85.0     B
3    David    60       70          65     65.0     C
4     Emma    85       95          90     90.0     A

In [ ]:
df['Final'] = df['Average'].apply(lambda x: "Pass" if x > 50 else "Fail")
df

      Name  Math  Science  Math_Bonus  Average Grade  Math_Bonuu Final
0    Alice    88       90          93     89.0     B          93  Pass
1      Bob    75       80          80     77.5     B          80  Pass
2  Charlie    92       78          97     85.0     B          97  Pass
3    David    60       70          65     65.0     C          65  Pass
4     Emma    85       95          90     90.0     A          90  Pass

In [ ]:
# MAP - works only on 1 column while .apply() works more and is much flexible then map, so just a single example of map
df['Name'] = df['Name'].map(str.upper)  # Map works only on one column, so we can apply the same funcs as of apply, but on 1 column only...
print(df)

      Name  Math  Science  Math_Bonus  Average Grade  Math_Bonuu Final
0    ALICE    88       90          93     89.0     B          93  Pass
1      BOB    75       80          80     77.5     B          80  Pass
2  CHARLIE    92       78          97     85.0     B          97  Pass
3    DAVID    60       70          65     65.0     C          65  Pass
4     EMMA    85       95          90     90.0     A          90  Pass