# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [ ]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "Chavid", "Chemma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
print("\n",b.dtypes,"\n")

# b['Age'] = b['Age'].astype(object)
# print(b.dtypes)

# b["Score"] = b['Score'].astype(str)
# print(b.dtypes)

# b['Name'] = b["Name"].astype("category")
# print(b.dtypes)


# b = b.astype({
#     "Age" : float,
#     "Score": str
# })
# print(b.dtypes)

 Name     object
Age       int64
Score     int64
dtype: object

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [ ]:
# print(b)

# Single replace
# b['Name'] = b['Name'].replace('Alice', 'New Alice')
# print(b)

# Multiple replace
# b['Name'] = b['Name'].replace({
#     'Bob': 'Tommy',
#     'Charlie': 'Paanchlie',
#     'Emma': 'Mumma'
# })
# print(b)

# b['Score'] = b['Score'].replace({
#     92 :'Excellent',
#     95:"Outstanding"
# })
# print(b)

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [ ]:
#1. Drop a single row by index -> drop(row_index)
# b.drop(2)
# print(b)

# #2. Multiple rows drop
# b.drop([2,4])

# #3. Dropping single column
# b.drop('Score', axis=1)

# #4. Dropping Multiple columns.
# b.drop(['Score','Name'], axis=1)
# print(b)

#5. Regex
# b['Name'] = b['Name'].replace({"Charlie":"Ch"},regex=True)
# print(b)


# b['Name'] = b['Name'].replace("^Ch.*","Ch",regex=True)
# print(b)


"""MY practice"""
# print(b)
# b = b.drop('Name', axis=1)
# print(b)

# b = b.drop(2, axis = 0) # drops the 2nd row, axis = 0 rows, axis=1, column
# print(b)

# Inplace = True means change the main data directly, and inplace=False, means don't change the main data, just change here temporarily.

# c = b.drop([1,3],axis = 0, inplace=False)
# print(c,"\n\n")
# print(b)

# b['Name']= b['Name'].replace({"Ti":"Chio"}, regex=True)
# print(b)

    Name   Age       City  Score
0  Alice  25.0      Delhi   85.0
1    Bob   NaN     Mumbai   91.0
2     Ch  35.0       None    NaN
3  David  40.0  Bangalore   88.0
4   Emma   NaN    Chennai   95.0

'MY practice'

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
# df.duplicated()
# df.duplicated().sum()


# df.duplicated()  # for checking duplicates -> Gives answer in boolean series form
# df.duplicated().sum()  # gives sum of all duplicates
# print(df,"\n\n")

# df.drop_duplicates()  # remove all duplicates

# #Remove duplicates and keep last occurence
# df.drop_duplicates(keep='last')   # Keep='last' means jaise 2 duplicate rows aayi tho unme se jo row last mai aayi hai vahi original row hai usko rakho
# # and jo row pehle aa rhi h usko hata do, and same with keep='first' usme first row rakho and last mai yaa uss row ke baad jo bhi aa rhi hai usko hata doo.

# #Remove duplicates and keep first occurence
# df.drop_duplicates(keep='first')

# print(df.drop_duplicates(subset=['Name']))   # Name column check karke usme se duplicated Names hatata hai, subset -> works on a specific column...


# regex was used in old pandas version, if you want to select a particular thing like in a database, if you want to update names starting with 'ch'
# So you can do it using regex, currently maybe the syntax is changed...

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [ ]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

# print("Original messy DataFrame:")
# print(df)

# 2. Handle missing values
# Fill or drop as needed

# print(df)
df = df.fillna(0)
# print(a)


# 3. Change data types
# Convert Age to int, Score to float, etc.

df['Age'] = df['Age'].astype(int)
df['Score'] = df['Score'].astype(float)


# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

df['City'] = df['City'].replace("Pun", "Pune")


# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want
df = df.drop("Extra", axis=1)

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()
df = df.drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()
# print(df.info())
df

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai    0.0
2  Chrlie    0       Pune   78.0
3   David   40  Bangalore   88.0
5       0   30     Mumbai   91.0

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.