#**Class 1**

##### Creating series

In [ ]:
import numpy as np
import pandas as pd
# Series are 1d

In [ ]:
labels = ['a','b', 'c']
my_list = [60,70,30]
arr = np.array([10,20,30])
d = {1:10, 2:20, 3:30}

In [ ]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
pd.Series(my_list)

0    60
1    70
2    30
dtype: int64

In [ ]:
pd.Series(my_list, labels)

a    60
b    70
c    30
dtype: int64

In [ ]:
pd.Series(my_list, index=d)

1    60
2    70
3    30
dtype: int64

In [ ]:
pd.Series(arr, index=my_list)

60    10
70    20
30    30
dtype: int64

In [ ]:
pd.Series(d, index=d)

1    10
2    20
3    30
dtype: int64

# **Class 2**

##### Creating a Dataframe

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 28],
    "City": ["New York", "London", "Paris", "Tokyo"],
    "Salary": [55000, 70000, 65000, 72000]
}
df  = pd.DataFrame(data)

In [ ]:
df

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   70000
2  Charlie   35     Paris   65000
3    David   28     Tokyo   72000

In [ ]:
students = [
    ["Alice", 20, "Math", 88],
    ["Bob", 22, "Physics", 91],
    ["Charlie", 21, "Chemistry", 85],
    ["David", 23, "Biology", 79],
    ["Eva", 20, "Computer Science", 95]
]
columns = ['name', 'age', 'subject', 'marks']
df2 = pd.DataFrame(students, columns=columns)

In [ ]:
df2

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

##### Selection and Indexing of columns

In [ ]:
df2

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

In [ ]:
df2['name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: name, dtype: object

In [ ]:
df2[['name', 'subject']]

      name           subject
0    Alice              Math
1      Bob           Physics
2  Charlie         Chemistry
3    David           Biology
4      Eva  Computer Science

#### Creating a new column

In [ ]:
df2['Class'] = [12,10,11,8,12]

In [ ]:
df2

      name  age           subject  marks  Class
0    Alice   20              Math     88     12
1      Bob   22           Physics     91     10
2  Charlie   21         Chemistry     85     11
3    David   23           Biology     79      8
4      Eva   20  Computer Science     95     12

##### Removing Columns

In [ ]:
df2.drop('Class', axis =  1)

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

In [ ]:
df2

      name  age           subject  marks  Class
0    Alice   20              Math     88     12
1      Bob   22           Physics     91     10
2  Charlie   21         Chemistry     85     11
3    David   23           Biology     79      8
4      Eva   20  Computer Science     95     12

In [ ]:
df2.drop('Class', axis = 1, inplace=True)

In [ ]:
df2

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

In [ ]:
df2['Class'] = [12,2,4,2,5]

In [ ]:
df2

      name  age           subject  marks  Class
0    Alice   20              Math     88     12
1      Bob   22           Physics     91      2
2  Charlie   21         Chemistry     85      4
3    David   23           Biology     79      2
4      Eva   20  Computer Science     95      5

In [ ]:
df2.drop(['Class', 'marks'], axis =1)

      name  age           subject
0    Alice   20              Math
1      Bob   22           Physics
2  Charlie   21         Chemistry
3    David   23           Biology
4      Eva   20  Computer Science

In [ ]:
df2

      name  age           subject  marks  Class
0    Alice   20              Math     88     12
1      Bob   22           Physics     91      2
2  Charlie   21         Chemistry     85      4
3    David   23           Biology     79      2
4      Eva   20  Computer Science     95      5

In [ ]:
df2['year'] = [22,22,24,24,25]

In [ ]:
df2

      name  age           subject  marks  Class  year
0    Alice   20              Math     88     12    22
1      Bob   22           Physics     91      2    22
2  Charlie   21         Chemistry     85      4    24
3    David   23           Biology     79      2    24
4      Eva   20  Computer Science     95      5    25

In [ ]:
df2.drop(['Class', 'year'], axis = 1)

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

In [ ]:
df2

      name  age           subject  marks  Class  year
0    Alice   20              Math     88     12    22
1      Bob   22           Physics     91      2    22
2  Charlie   21         Chemistry     85      4    24
3    David   23           Biology     79      2    24
4      Eva   20  Computer Science     95      5    25

In [ ]:
df2.drop(['Class', 'year'], axis=1, inplace=True)

In [ ]:
df2

      name  age           subject  marks
0    Alice   20              Math     88
1      Bob   22           Physics     91
2  Charlie   21         Chemistry     85
3    David   23           Biology     79
4      Eva   20  Computer Science     95

In [ ]:
df2[['class','year']] = [
    [12,22],
    [5,23],
    [6,5],
    [11, 22],
    [8, 20]
]

In [ ]:
df2

      name  age           subject  marks  class  year
0    Alice   20              Math     88     12    22
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2.drop(0, axis=0)

      name  age           subject  marks  class  year
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2

      name  age           subject  marks  class  year
0    Alice   20              Math     88     12    22
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2.drop(0, axis=0, inplace=True)

In [ ]:
df2

      name  age           subject  marks  class  year
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

#####  Selecting rows

In [ ]:
df2

      name  age           subject  marks  class  year
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2.loc[1:3]

      name  age    subject  marks  class  year
1      Bob   22    Physics     91      5    23
2  Charlie   21  Chemistry     85      6     5
3    David   23    Biology     79     11    22

#####Selecting Subsets of Rows and Columns

In [ ]:
df2

      name  age           subject  marks  class  year
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2.loc[[1,2]][['marks','class']]

   marks  class
1     91      5
2     85      6

In [ ]:
df2.loc[[1,3]][['subject', 'marks']]

   subject  marks
1  Physics     91
3  Biology     79

In [ ]:
df2

      name  age           subject  marks  class  year
1      Bob   22           Physics     91      5    23
2  Charlie   21         Chemistry     85      6     5
3    David   23           Biology     79     11    22
4      Eva   20  Computer Science     95      8    20

In [ ]:
df2.loc[[3,4]][['name','age']]

    name  age
3  David   23
4    Eva   20

#####Conditional Selection

In [ ]:
df

      Name  Age      City  Salary
0    Alice   25  New York   55000
1      Bob   30    London   70000
2  Charlie   35     Paris   65000
3    David   28     Tokyo   72000

In [ ]:
# Age > 30
df[df['Age'] >= 30]

      Name  Age    City  Salary
1      Bob   30  London   70000
2  Charlie   35   Paris   65000

In [ ]:
df[(df['Age']> 30) & (df['City'] == 'Paris')]

      Name  Age   City  Salary
2  Charlie   35  Paris   65000

# **Class 2**

##### Finding missing data

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Neha', 'Karan'],
    'Maths': [85, 65, np.nan, 91, 55],
    'Science': [78, np.nan, 40, 95, 60],
    'English': [92, 70, 30, np.nan, 58],
    'Total': [255, np.nan, 105, np.nan, 173]
})
df

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0      NaN     70.0    NaN
2  Rahul    NaN     40.0     30.0  105.0
3   Neha   91.0     95.0      NaN    NaN
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
df.isna()

    Name  Maths  Science  English  Total
0  False  False    False    False  False
1  False  False     True    False   True
2  False   True    False    False  False
3  False  False    False     True   True
4  False  False    False    False  False

In [ ]:
df.isna().sum()

Name       0
Maths      1
Science    1
English    1
Total      2
dtype: int64

In [ ]:
df.isna().any()

Name       False
Maths       True
Science     True
English     True
Total       True
dtype: bool

##### Removing missing values

In [ ]:
df

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0      NaN     70.0    NaN
2  Rahul    NaN     40.0     30.0  105.0
3   Neha   91.0     95.0      NaN    NaN
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
df.dropna()

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
df.dropna(thresh=3)

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0      NaN     70.0    NaN
2  Rahul    NaN     40.0     30.0  105.0
3   Neha   91.0     95.0      NaN    NaN
4  Karan   55.0     60.0     58.0  173.0

##### Filling the missing data

In [ ]:
df

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0      NaN     70.0    NaN
2  Rahul    NaN     40.0     30.0  105.0
3   Neha   91.0     95.0      NaN    NaN
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
values = {'Name':0, 'Maths' : 100, 'Science': 300, 'English' : 5050, 'Total' : 9590}
df.fillna(values)

    Name  Maths  Science  English   Total
0   Aman   85.0     78.0     92.0   255.0
1   Riya   65.0    300.0     70.0  9590.0
2  Rahul  100.0     40.0     30.0   105.0
3   Neha   91.0     95.0   5050.0  9590.0
4  Karan   55.0     60.0     58.0   173.0

In [ ]:
df.fillna(0)

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0      0.0     70.0    0.0
2  Rahul    0.0     40.0     30.0  105.0
3   Neha   91.0     95.0      0.0    0.0
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
df.fillna(df.sum())

    Name  Maths  Science  English  Total
0   Aman   85.0     78.0     92.0  255.0
1   Riya   65.0    273.0     70.0  533.0
2  Rahul  296.0     40.0     30.0  105.0
3   Neha   91.0     95.0    250.0  533.0
4  Karan   55.0     60.0     58.0  173.0

In [ ]:
df.fillna(df.mean(numeric_only=True))

    Name  Maths  Science  English       Total
0   Aman   85.0    78.00     92.0  255.000000
1   Riya   65.0    68.25     70.0  177.666667
2  Rahul   74.0    40.00     30.0  105.000000
3   Neha   91.0    95.00     62.5  177.666667
4  Karan   55.0    60.00     58.0  173.000000

# **Class 3**

##### Merging 2 Dataframes

In [ ]:
import pandas as pd
import numpy as np

# DataFrame 1: Employee information
emp = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
sal = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
emp

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [ ]:
sal

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(emp, sal, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(emp, sal, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(emp, sal, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(emp, sal, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

##### Concatination of 2 Dataframes

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [ ]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

##### Joining 2 Dataframes

In [ ]:
import pandas as pd

# First DataFrame
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [ ]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [ ]:
df1.join(df2 ,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# **Class 4**

##### Groupby

In [ ]:
import numpy as np
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
multi = df.groupby(['Category','Store'])['Sales'].sum()
multi

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

##### Aggregation

In [ ]:
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].max()

300

In [ ]:
df['Sales'].median()

190.0

In [ ]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [ ]:
df['Sales'].std()

66.06274074155351

In [ ]:
df['Sales'].min()

100

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].agg(['mean','sum','min','max','count'])

mean      187.5
sum      1500.0
min       100.0
max       300.0
count       8.0
Name: Sales, dtype: float64

In [ ]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

# **Class 5**

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

##### Pivot tables

In [ ]:

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South',
        'East', 'West', 'North', 'South'
    ],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice',
        'John', 'Mary', 'Bob', 'Alice'
    ]
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [ ]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    448     50   John  January      Q1
1  2023-01-02       B   West    507     79   Mary  January      Q1
2  2023-01-03       C  North    744     56    Bob  January      Q1
3  2023-01-04       D  South    242     15  Alice  January      Q1
4  2023-01-05       A   East    869     61   John  January      Q1
5  2023-01-06       B   West    545     86   Mary  January      Q1
6  2023-01-07       C  North    561     32    Bob  January      Q1
7  2023-01-08       D  South    650     57  Alice  January      Q1
8  2023-01-09       A   East    787     12   John  January      Q1
9  2023-01-10       B   West    220     31   Mary  January      Q1
10 2023-01-11       C  North    595     42    Bob  January      Q1
11 2023-01-12       D  South    418     17  Alice  January      Q1
12 2023-01-13       A   East    516     53   John  January      Q1
13 2023-01-14       B   West    295     53   Mary  January      Q1
14 2023-01-15       C  North    267     28    Bob  January      Q1
15 2023-01-16       D  South    203     85  Alice  January      Q1
16 2023-01-17       A   East    484     49   John  January      Q1
17 2023-01-18       B   West    339     60   Mary  January      Q1
18 2023-01-19       C  North    258     27    Bob  January      Q1
19 2023-01-20       D  South    857     30  Alice  January      Q1

In [ ]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     516.0    NaN    NaN    NaN
North      NaN    NaN  561.0    NaN
South      NaN    NaN    NaN  418.0
West       NaN  339.0    NaN    NaN

In [ ]:
pd.pivot_table(df, values = ['Sales','Units'], index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     620.8    NaN    NaN    NaN  45.0   NaN   NaN   NaN
North      NaN    NaN  485.0    NaN   NaN   NaN  37.0   NaN
South      NaN    NaN    NaN  474.0   NaN   NaN   NaN  40.8
West       NaN  381.2    NaN    NaN   NaN  61.8   NaN   NaN

##### Cross Tabs

In [ ]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# **Class 6**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({
    "A": [1, 2, 3, 4, 5],
    "B": [10, 20,30,40,50],
    "C": [100,200,300,400,500]
})
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df.shape

(5, 3)

In [ ]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
# df['B']**2

In [ ]:
def square(x):
  return x**2
df['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df['B'] = df['B'].apply(square)
df

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [ ]:
df['D'] = df['A'].apply(square)
df

   A     B    C   D
0  1   100  100   1
1  2   400  200   4
2  3   900  300   9
3  4  1600  400  16
4  5  2500  500  25

In [ ]:
df['E'] = df['B'].apply(lambda x:x**2)
df

   A     B    C   D        E
0  1   100  100   1    10000
1  2   400  200   4   160000
2  3   900  300   9   810000
3  4  1600  400  16  2560000
4  5  2500  500  25  6250000

# **Feature Engineering**

In [ ]:
import pandas as pd
import random

titles = [
    "Fullmetal Alchemist: Brotherhood","Steins;Gate","Bleach: Thousand Year War",
    "Gintama°","Attack on Titan Season 3 Part 2","Hunter x Hunter (2011)",
    "Code Geass R2","Death Note","Vinland Saga","Demon Slayer",
    "Jujutsu Kaisen","One Piece","Naruto Shippuden","Chainsaw Man",
    "Mob Psycho 100","Spy x Family","Haikyuu!!","Monster",
    "Cowboy Bebop","Black Clover","Blue Lock","Parasyte","Erased",
    "Your Lie in April","Dr. Stone","Psycho-Pass",
    "Neon Genesis Evangelion","Baccano!","Made in Abyss","Kaguya-sama",
    "Re:Zero","Mushoku Tensei","Tokyo Revengers","86 Eighty-Six",
    "JoJo Part 5","Fruits Basket","Odd Taxi","Dororo",
    "Great Teacher Onizuka","Samurai Champloo","Fire Force",
    "No Game No Life","Overlord","The Promised Neverland",
    "Violet Evergarden","Akame ga Kill!","Charlotte",
    "Noragami","Hellsing Ultimate","Blue Exorcist"
]

types = ["TV","Movie","OVA","ONA","Special"]
months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

rows = []

for rank, title in enumerate(titles, start=1):

    anime_type = random.choice(types)

    eps = 1 if anime_type == "Movie" else random.randint(10,150)

    start_year = random.randint(2005,2023)
    start_month = random.choice(months)

    if anime_type == "Movie":
        end_date = "-"
    else:
        end_year = start_year + random.randint(0,2)
        end_month = random.choice(months)
        end_date = f"{end_month} {end_year}"

    members = f"{random.randint(150000,4500000):,}"

    score = round(random.uniform(7.50,9.30),2)

    title_col = (
        f"{title}"
        f"{anime_type} "
        f"({eps} eps)"
        f"{start_month} {start_year} - {end_date}"
        f"{members} members"
    )

    rows.append([rank, title_col, score])

df = pd.DataFrame(rows, columns=["Rank","Title","Score"])

# print(df.head())
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (106 eps)Ju...   8.90
1     2  Steins;GateOVA (83 eps)Feb 2022 - Dec 20243,92...   8.66
2     3  Bleach: Thousand Year WarONA (149 eps)Aug 2008...   7.96
3     4  Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,7...   8.15
4     5  Attack on Titan Season 3 Part 2OVA (82 eps)Feb...   9.09

In [ ]:
df.loc[4]['Title']

'Attack on Titan Season 3 Part 2OVA (82 eps)Feb 2021 - May 20232,397,297 members'

In [ ]:
# def extract_episode(txt):
#   check= False
#   data = ""

#   for i in txt:
#     if i == "(":
#       check = True
#       continue

#     if i == ")":
#       break

#     if check == True:
#       data += i

#   return data

# df['Episode'] = df['Title'].apply(extract_episode)

In [ ]:
df['Episode'] = df['Title'].str.extract(r'(\d+)\s*eps').astype(int)

In [ ]:
df.head(7)

,Rank,Title,Score,Episode,Date,Duration Months
0,1,Fullmetal Alchemist: BrotherhoodTV (106 eps)Ju...,8.90,106,Jun 2006 - Mar 2008,33
1,2,"Steins;GateOVA (83 eps)Feb 2022 - Dec 20243,92...",8.66,83,Feb 2022 - Dec 2024,38
2,3,Bleach: Thousand Year WarONA (149 eps)Aug 2008...,7.96,149,Aug 2008 - Aug 2009,28
3,4,"Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,7...",8.15,37,Sep 2014 - Sep 2015,30
4,5,Attack on Titan Season 3 Part 2OVA (82 eps)Feb...,9.09,82,Feb 2021 - May 2023,31
5,6,Hunter x Hunter (2011)Movie (1 eps)Dec 2014 - ...,8.81,1,NaN,0
6,7,"Code Geass R2TV (56 eps)Jun 2022 - Aug 20223,2...",8.04,56,Jun 2022 - Aug 2022,14

In [ ]:
df['Episode'].dtype

dtype('int64')

In [ ]:
# df['Episode'] = df['Episode'].str.replace(" eps", "")

In [ ]:
# df['Title'] = df['Title'].str.replace(r"\(.*?\)", "", regex=True)

df['Episode'] = df['Episode'].astype(int)
df.head()

,Rank,Title,Score,Episode,Date,Duration Months
0,1,Fullmetal Alchemist: BrotherhoodTV (106 eps)Ju...,8.90,106,Jun 2006 - Mar 2008,33
1,2,"Steins;GateOVA (83 eps)Feb 2022 - Dec 20243,92...",8.66,83,Feb 2022 - Dec 2024,38
2,3,Bleach: Thousand Year WarONA (149 eps)Aug 2008...,7.96,149,Aug 2008 - Aug 2009,28
3,4,"Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,7...",8.15,37,Sep 2014 - Sep 2015,30
4,5,Attack on Titan Season 3 Part 2OVA (82 eps)Feb...,9.09,82,Feb 2021 - May 2023,31

In [ ]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (106 eps)Jun 2006 - Mar 20081,901,563 members'

In [ ]:
# def extract_date(txt):
#   data = ""
#   for i in range(len(txt)):
#     if txt[i] == ")":
#       for j in range(i+1, i+20):
#         data +=  txt[j]
#       return data

df["Date"] = df["Title"].str.extract(r"([A-Z][a-z]{2}\s\d{4}\s-\s[A-Z][a-z]{2}\s\d{4})")

In [ ]:
# df['Date'] = df['Title'].apply(extract_date)
df.head()

,Rank,Title,Score,Episode,Date,Duration Months
0,1,Fullmetal Alchemist: BrotherhoodTV (106 eps)Ju...,8.90,106,Jun 2006 - Mar 2008,33
1,2,"Steins;GateOVA (83 eps)Feb 2022 - Dec 20243,92...",8.66,83,Feb 2022 - Dec 2024,38
2,3,Bleach: Thousand Year WarONA (149 eps)Aug 2008...,7.96,149,Aug 2008 - Aug 2009,28
3,4,"Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,7...",8.15,37,Sep 2014 - Sep 2015,30
4,5,Attack on Titan Season 3 Part 2OVA (82 eps)Feb...,9.09,82,Feb 2021 - May 2023,31

In [ ]:
df.loc[3]['Title']

'Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,747 members'

In [ ]:
dates = df['Date'].str.split(' - ', expand=True)
start = pd.to_datetime(dates[0], format = '%b %Y')
end = pd.to_datetime(dates[1], format = '%b %Y')

df['Duration Months'] = (end.dt.year - start.dt.year) * 12 + (end.dt.month + start.dt.month)
df['Duration Months'] = df['Duration Months'].fillna(0).astype(int)

df.head(7)


# # Split start and end dates
# dates = df['Date'].str.split(' - ', expand=True)

# # Convert to datetime
# start = pd.to_datetime(dates[0], format='%b %Y')
# end = pd.to_datetime(dates[1], format='%b %Y')

# # Calculate duration in months
# df['Duration_Months'] = (end.dt.year - start.dt.year) * 12 + (end.dt.month - start.dt.month)

,Rank,Title,Score,Episode,Date,Duration Months
0,1,Fullmetal Alchemist: BrotherhoodTV (106 eps)Ju...,8.90,106,Jun 2006 - Mar 2008,33
1,2,"Steins;GateOVA (83 eps)Feb 2022 - Dec 20243,92...",8.66,83,Feb 2022 - Dec 2024,38
2,3,Bleach: Thousand Year WarONA (149 eps)Aug 2008...,7.96,149,Aug 2008 - Aug 2009,28
3,4,"Gintama°ONA (37 eps)Sep 2014 - Sep 20152,859,7...",8.15,37,Sep 2014 - Sep 2015,30
4,5,Attack on Titan Season 3 Part 2OVA (82 eps)Feb...,9.09,82,Feb 2021 - May 2023,31
5,6,Hunter x Hunter (2011)Movie (1 eps)Dec 2014 - ...,8.81,1,NaN,0
6,7,"Code Geass R2TV (56 eps)Jun 2022 - Aug 20223,2...",8.04,56,Jun 2022 - Aug 2022,14

In [ ]:
# which anime has the highest score
df['Score'].max()

9.29

In [ ]:
df['Score'].nlargest(5)

26    9.29
17    9.27
46    9.24
19    9.21
23    9.21
Name: Score, dtype: float64

In [ ]:
df['Episode'].max()

149

In [ ]:
df.loc[df['Episode'].idxmax()]

Rank                                                               3
Title              Bleach: Thousand Year WarONA (149 eps)Aug 2008...
Score                                                           7.96
Episode                                                          149
Date                                             Aug 2008 - Aug 2009
Duration Months                                                   28
Name: 2, dtype: object

In [ ]:
df.loc[df['Episode'].idxmin()]

Rank                                                               6
Title              Hunter x Hunter (2011)Movie (1 eps)Dec 2014 - ...
Score                                                           8.81
Episode                                                            1
Date                                                             NaN
Duration Months                                                    0
Name: 5, dtype: object

In [ ]:
df.loc[df['Episode'].nlargest(5).index]

,Rank,Title,Score,Episode,Date,Duration Months
2,3,Bleach: Thousand Year WarONA (149 eps)Aug 2008...,7.96,149,Aug 2008 - Aug 2009,28
23,24,Your Lie in AprilSpecial (149 eps)Jan 2006 - J...,9.21,149,Jan 2006 - Jul 2007,20
10,11,Jujutsu KaisenONA (147 eps)Sep 2007 - Dec 2009...,8.68,147,Sep 2007 - Dec 2009,45
37,38,"DororoTV (137 eps)Sep 2017 - Mar 20194,400,751...",8.38,137,Sep 2017 - Mar 2019,36
13,14,"Chainsaw ManONA (131 eps)Nov 2021 - Dec 20222,...",8.84,131,Nov 2021 - Dec 2022,35

In [ ]:
df.loc[df['Duration Months'].idxmax()]

Rank                                                              11
Title              Jujutsu KaisenONA (147 eps)Sep 2007 - Dec 2009...
Score                                                           8.68
Episode                                                          147
Date                                             Sep 2007 - Dec 2009
Duration Months                                                   45
Name: 10, dtype: object

# **Class 7**

In [ ]:
df = pd.read_csv('Countries.csv')
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [ ]:
df.loc[df['population'].idxmax(), ['country', 'population']]

country            India
population    1417173173
Name: 75, dtype: object

In [ ]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
df.loc[df['population'].idxmax(), 'capital_city']

'New Delhi'

In [ ]:
df.loc[df['population'].idxmin(), 'country']

'Tuvalu'

In [ ]:
df.loc[df['population'].idxmin(), 'capital_city']

'Funafuti'

In [ ]:
df.loc[df['democracy_score'].nlargest(5).index]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [ ]:
df['region'].count()

np.int64(194)

In [ ]:
df[df['region']=='Eastern Europe']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.0,82810.0,...,9208701,40.0000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.0,50470.0,...,6465097,24.1667,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.5,35238.7,...,10526073,25.5000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.0,49030.0,...,9683505,14.0704,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister
111,Moldova,Republic of Moldova,Moldovan leu,Chișinău,Eastern Europe,Europe,Moldovan,47.000000,29.0,22646.0,...,2592477,40.5941,1473227,1119250,2.51,5.85,Hybrid regime,31.2,Ion Chicu,Prime Minister
136,Poland,Republic of Poland,Polish zloty,Warsaw,Eastern Europe,Europe,Polish,52.000000,20.0,144610.0,...,37561599,28.2609,14974307,22587292,2.71,6.67,Flawed democracy,36.3,Mateusz Morawiecki,Prime Minister
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.0,135910.0,...,18956666,19.0909,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.000000,100.0,2154940.0,...,143555736,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.5,18830.0,...,5431752,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.0,413110.0,...,38000000,20.3310,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President

In [ ]:
# df['country'].unique()

In [ ]:
df['region'].unique()

array(['Southern Asia', 'Southern Europe', 'Northern Africa',
       'Middle Africa', 'Caribbean', 'South America', 'Western Asia',
       'Australia and New Zealand', 'Western Europe', 'Eastern Europe',
       'Central America', 'Western Africa', 'Southern Africa',
       'South-Eastern Asia', 'Eastern Africa', 'Northern America',
       'Eastern Asia', 'Northern Europe', 'Melanesia', 'Central Asia',
       'Micronesia', 'Polynesia'], dtype=object)

In [ ]:
# sorted(df['region'].unique())

In [ ]:
# sorted(df['country'].unique())

In [ ]:
# sorte = sorted(df['population'])
# sorte.loc[1]['political party']
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
# df[df['population'].nlargest(2),'political leader']
df.nlargest(2, 'population').iloc[1]['political_leader']

'Xi Jinping'

In [ ]:
df.nlargest(5,'population').iloc[2]['political_leader']

'Joe Biden'

In [ ]:
df['political_leader'].isna().sum()

np.int64(7)

In [ ]:
# df['country_long'].unique()

In [ ]:
df['country_long'].str.contains('Republic', na=False).sum()

np.int64(125)

In [ ]:
df['region'].unique()

array(['Southern Asia', 'Southern Europe', 'Northern Africa',
       'Middle Africa', 'Caribbean', 'South America', 'Western Asia',
       'Australia and New Zealand', 'Western Europe', 'Eastern Europe',
       'Central America', 'Western Africa', 'Southern Africa',
       'South-Eastern Asia', 'Eastern Africa', 'Northern America',
       'Eastern Asia', 'Northern Europe', 'Melanesia', 'Central Asia',
       'Micronesia', 'Polynesia'], dtype=object)

In [ ]:
df['population']

In [ ]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
# africa = df[df['region'] == 'Africa']
# africa.loc[africa['population'].idxmax(), ['country_long', 'population']]

africa = df[df['region'].str.contains('Africa', na=False)]
africa.loc[africa['population'].idxmax(), 'country_long']

'Federal Republic of Nigeria'