In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    'Name' : ['Aman', 'Riya', 'Rahul'],
    'Age': [20,21,19],
    'City' :['Bhopal', 'Indore', 'Delhi']
}
df = pd.DataFrame(data)

In [ ]:
df

    Name  Age    City
0   Aman   20  Bhopal
1   Riya   21  Indore
2  Rahul   19   Delhi

In [ ]:
d = {
    "Product": ["Pen", "Book", "Bag"],
    "Price": [10, 50, 500]
}
df = pd.DataFrame(d)
df

  Product  Price
0     Pen     10
1    Book     50
2     Bag    500

In [ ]:
data = {
    'Name' : ['Aman', 'Rahul','Rahul ka dost','Aman ka dost', 'dost ka dost'],
    'Maths' : [34,54,33,56,76],
    'Science' : [23,54,65,33,75],
    'English': [55,66,45,64,43]
}
df = pd.DataFrame(data)
df

            Name  Maths  Science  English
0           Aman     34       23       55
1          Rahul     54       54       66
2  Rahul ka dost     33       65       45
3   Aman ka dost     56       33       64
4   dost ka dost     76       75       43

In [ ]:
df['Name']

0             Aman
1            Rahul
2    Rahul ka dost
3     Aman ka dost
4     dost ka dost
Name: Name, dtype: object

In [ ]:
df

            Name  Maths  Science  English
0           Aman     34       23       55
1          Rahul     54       54       66
2  Rahul ka dost     33       65       45
3   Aman ka dost     56       33       64
4   dost ka dost     76       75       43

In [ ]:
df[['Name', 'Science']]

            Name  Science
0           Aman       23
1          Rahul       54
2  Rahul ka dost       65
3   Aman ka dost       33
4   dost ka dost       75

In [ ]:
df.dtypes

Name       object
Maths       int64
Science     int64
English     int64
dtype: object

In [ ]:
df['Name'].dtypes

dtype('O')

In [ ]:
df['Science'].dtype

dtype('int64')

In [ ]:
df[['Name', 'Science']].dtypes

Name       object
Science     int64
dtype: object

In [ ]:
df

            Name  Maths  Science  English
0           Aman     34       23       55
1          Rahul     54       54       66
2  Rahul ka dost     33       65       45
3   Aman ka dost     56       33       64
4   dost ka dost     76       75       43

In [ ]:
df.count()

Name       5
Maths      5
Science    5
English    5
dtype: int64

In [ ]:
rows, columns = df.shape
rows, columns

(5, 4)

In [ ]:
df.shape

(5, 4)

In [ ]:
df['total'] = df['Science'] + df['Maths'] + df['English']
df

            Name  Maths  Science  English  total
0           Aman     34       23       55    112
1          Rahul     54       54       66    174
2  Rahul ka dost     33       65       45    143
3   Aman ka dost     56       33       64    153
4   dost ka dost     76       75       43    194

In [ ]:
df['Avg'] = df[['Science','Maths','English']].mean(axis=1)

In [ ]:
df

            Name  Maths  Science  English  total        Avg
0           Aman     34       23       55    112  37.333333
1          Rahul     54       54       66    174  58.000000
2  Rahul ka dost     33       65       45    143  47.666667
3   Aman ka dost     56       33       64    153  51.000000
4   dost ka dost     76       75       43    194  64.666667

In [ ]:
df['result'] = np.where(df['Avg']>= 40, "Pass", 'Fail')

In [ ]:
df

            Name  Maths  Science  English  total        Avg result
0           Aman     34       23       55    112  37.333333   Fail
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df.drop('Avg', axis=1)

            Name  Maths  Science  English  total result
0           Aman     34       23       55    112   Fail
1          Rahul     54       54       66    174   Pass
2  Rahul ka dost     33       65       45    143   Pass
3   Aman ka dost     56       33       64    153   Pass
4   dost ka dost     76       75       43    194   Pass

In [ ]:
df

            Name  Maths  Science  English  total        Avg result
0           Aman     34       23       55    112  37.333333   Fail
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df.iloc[1]

Name       Rahul
Maths         54
Science       54
English       66
total        174
Avg         58.0
result      Pass
Name: 1, dtype: object

In [ ]:
df.iloc[1:4]

            Name  Maths  Science  English  total        Avg result
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass

In [ ]:
df.iloc[2:5]

            Name  Maths  Science  English  total        Avg result
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df.iloc[2:, :2]

            Name  Maths
2  Rahul ka dost     33
3   Aman ka dost     56
4   dost ka dost     76

In [ ]:
df

            Name  Maths  Science  English  total        Avg result
0           Aman     34       23       55    112  37.333333   Fail
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df.iloc[3:]

           Name  Maths  Science  English  total        Avg result
3  Aman ka dost     56       33       64    153  51.000000   Pass
4  dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df.iloc[3:, [3,4]]

   English  total
3       64    153
4       43    194

In [ ]:
mark = df['Maths'].apply(lambda x : x>50)
df[mark]

           Name  Maths  Science  English  total        Avg result
1         Rahul     54       54       66    174  58.000000   Pass
3  Aman ka dost     56       33       64    153  51.000000   Pass
4  dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
df

            Name  Maths  Science  English  total        Avg result
0           Aman     34       23       55    112  37.333333   Fail
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
3   Aman ka dost     56       33       64    153  51.000000   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
marks = df[['Science', 'English']].apply(lambda x: (x['Science']>35) & (x['English']>40), axis=1)
df[marks]

            Name  Maths  Science  English  total        Avg result
1          Rahul     54       54       66    174  58.000000   Pass
2  Rahul ka dost     33       65       45    143  47.666667   Pass
4   dost ka dost     76       75       43    194  64.666667   Pass

In [ ]:
# df['Avg'].apply(lambda x: (x['Avg'] > 60) & (x['Avg'] < 80))
df['Avg'] = df['Avg'].astype(int)
df

            Name  Maths  Science  English  total  Avg result
0           Aman     34       23       55    112   37   Fail
1          Rahul     54       54       66    174   58   Pass
2  Rahul ka dost     33       65       45    143   47   Pass
3   Aman ka dost     56       33       64    153   51   Pass
4   dost ka dost     76       75       43    194   64   Pass

In [ ]:
Averag = df['Avg'].apply(lambda x: (x>50) & (x< 80))
df[Averag]

           Name  Maths  Science  English  total  Avg result
1         Rahul     54       54       66    174   58   Pass
3  Aman ka dost     56       33       64    153   51   Pass
4  dost ka dost     76       75       43    194   64   Pass

In [ ]:
import pandas as pd

df2 = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Neha', 'Karan'],
    'Maths': [85, 65, 35, 91, 55],
    'Science': [78, 88, 40, 95, 60],
    'English': [92, 70, 30, 89, 58]
})
df2

    Name  Maths  Science  English
0   Aman     85       78       92
1   Riya     65       88       70
2  Rahul     35       40       30
3   Neha     91       95       89
4  Karan     55       60       58

In [ ]:
df2['total'] = df2[['Maths', 'Science', 'English']].sum(axis=1)
df2

    Name  Maths  Science  English  total
0   Aman     85       78       92    255
1   Riya     65       88       70    223
2  Rahul     35       40       30    105
3   Neha     91       95       89    275
4  Karan     55       60       58    173

In [ ]:
df2['avg'] = df2[['Science', 'Maths','English']].mean(axis=1)
df2['avg'] = df2['avg'].astype(int)

In [ ]:
df2

    Name  Maths  Science  English  total  avg
0   Aman     85       78       92    255   85
1   Riya     65       88       70    223   74
2  Rahul     35       40       30    105   35
3   Neha     91       95       89    275   91
4  Karan     55       60       58    173   57

In [ ]:
df2['result'] = df2['avg'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
df2

    Name  Maths  Science  English  total  avg result
0   Aman     85       78       92    255   85   Pass
1   Riya     65       88       70    223   74   Pass
2  Rahul     35       40       30    105   35   Fail
3   Neha     91       95       89    275   91   Pass
4  Karan     55       60       58    173   57   Pass

In [ ]:
passed = df2['avg'] >= 40
df[passed]

           Name  Maths  Science  English  total  Avg result
0          Aman     34       23       55    112   37   Fail
1         Rahul     54       54       66    174   58   Pass
3  Aman ka dost     56       33       64    153   51   Pass
4  dost ka dost     76       75       43    194   64   Pass

In [ ]:
greater = df2['total'] > 240
df[greater]

           Name  Maths  Science  English  total  Avg result
0          Aman     34       23       55    112   37   Fail
3  Aman ka dost     56       33       64    153   51   Pass

In [ ]:
df2

    Name  Maths  Science  English  total  avg result
0   Aman     85       78       92    255   85   Pass
1   Riya     65       88       70    223   74   Pass
2  Rahul     35       40       30    105   35   Fail
3   Neha     91       95       89    275   91   Pass
4  Karan     55       60       58    173   57   Pass

In [ ]:
great = df2['Science']>80
df2[great][['Name','avg']]

   Name  avg
1  Riya   74
3  Neha   91

In [ ]:
df2.drop('total', axis=1)

    Name  Maths  Science  English  avg result
0   Aman     85       78       92   85   Pass
1   Riya     65       88       70   74   Pass
2  Rahul     35       40       30   35   Fail
3   Neha     91       95       89   91   Pass
4  Karan     55       60       58   57   Pass

In [ ]:
df2

    Name  Maths  Science  English  total  avg result
0   Aman     85       78       92    255   85   Pass
1   Riya     65       88       70    223   74   Pass
2  Rahul     35       40       30    105   35   Fail
3   Neha     91       95       89    275   91   Pass
4  Karan     55       60       58    173   57   Pass

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul", "Neha"],
    "Age": [20, np.nan, 19, 22],
    "City": ["Bhopal", "Indore", np.nan, "Delhi"]
})

print(df)

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya   NaN  Indore
2  Rahul  19.0     NaN
3   Neha  22.0   Delhi

In [ ]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [ ]:
df.isna().sum()

Name    0
Age     1
City    1
dtype: int64

In [ ]:
df.isna().sum().sum()

np.int64(2)

In [ ]:
df

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya   NaN  Indore
2  Rahul  19.0     NaN
3   Neha  22.0   Delhi

In [ ]:
df['Age'] = df['Age'].fillna(18)

In [ ]:
df

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya  18.0  Indore
2  Rahul  19.0     NaN
3   Neha  22.0   Delhi

In [ ]:
df['City']= df['City'].fillna('Uknown')

In [ ]:
df

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya  18.0  Indore
2  Rahul  19.0  Uknown
3   Neha  22.0   Delhi

In [ ]:
df.fillna(0)

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya  18.0  Indore
2  Rahul  19.0  Uknown
3   Neha  22.0   Delhi

In [ ]:
df

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya  18.0  Indore
2  Rahul  19.0  Uknown
3   Neha  22.0   Delhi

In [ ]:
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul", "Neha"],
    "Age": [20, np.nan, 19, 22],
    "City": ["Bhopal", "Indore", np.nan, "Delhi"]
})
df

    Name   Age    City
0   Aman  20.0  Bhopal
1   Riya   NaN  Indore
2  Rahul  19.0     NaN
3   Neha  22.0   Delhi

In [ ]:
df.dropna()

   Name   Age    City
0  Aman  20.0  Bhopal
3  Neha  22.0   Delhi

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul", "Neha"],
    "Age": [20, np.nan, 19, np.nan],
    "City": [np.nan, "Indore", "Delhi", np.nan]
})

df

    Name   Age    City
0   Aman  20.0     NaN
1   Riya   NaN  Indore
2  Rahul  19.0   Delhi
3   Neha   NaN     NaN

In [ ]:
df.isna()

    Name    Age   City
0  False  False   True
1  False   True  False
2  False  False  False
3  False   True   True

In [ ]:
df

    Name   Age    City
0   Aman  20.0     NaN
1   Riya   NaN  Indore
2  Rahul  19.0   Delhi
3   Neha   NaN     NaN

In [ ]:
df.dropna(axis=1, how='all')

    Name   Age    City
0   Aman  20.0     NaN
1   Riya   NaN  Indore
2  Rahul  19.0   Delhi
3   Neha   NaN     NaN

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul", "Neha"],
    "Maths": [85, np.nan, 45, 95],
    "Science": [np.nan, 78, 55, 98],
    "English": [90, 80, np.nan, 99]
})

df

    Name  Maths  Science  English
0   Aman   85.0      NaN     90.0
1   Riya    NaN     78.0     80.0
2  Rahul   45.0     55.0      NaN
3   Neha   95.0     98.0     99.0

In [ ]:
df.isna()

    Name  Maths  Science  English
0  False  False     True    False
1  False   True    False    False
2  False  False    False     True
3  False  False    False    False

In [ ]:
df.fillna(0)

    Name  Maths  Science  English
0   Aman   85.0      0.0     90.0
1   Riya    0.0     78.0     80.0
2  Rahul   45.0     55.0      0.0
3   Neha   95.0     98.0     99.0

In [ ]:
df.isna()

    Name  Maths  Science  English
0  False  False     True    False
1  False   True    False    False
2  False  False    False     True
3  False  False    False    False

In [ ]:
df[df['Science'].notna()]

    Name  Maths  Science  English
1   Riya    NaN     78.0     80.0
2  Rahul   45.0     55.0      NaN
3   Neha   95.0     98.0     99.0

In [ ]:
import pandas as pd
import numpy as np

# Create DataFrame
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Rahul", "Neha", "Karan"],
    "Salary": [50000, np.nan, 45000, 60000, np.nan],
    "Department": ["IT", "HR", np.nan, "Finance", "IT"],
    "Experience": [2, 3, np.nan, 5, 1]
})

df

    Name   Salary Department  Experience
0   Aman  50000.0         IT         2.0
1   Riya      NaN         HR         3.0
2  Rahul  45000.0        NaN         NaN
3   Neha  60000.0    Finance         5.0
4  Karan      NaN         IT         1.0

In [ ]:
df.isna()

    Name  Salary  Department  Experience
0  False   False       False       False
1  False    True       False       False
2  False   False        True        True
3  False   False       False       False
4  False    True       False       False

In [ ]:
df.isna().sum()

Name          0
Salary        2
Department    1
Experience    1
dtype: int64

In [ ]:
df

    Name   Salary Department  Experience
0   Aman  50000.0         IT         2.0
1   Riya      NaN         HR         3.0
2  Rahul  45000.0        NaN         NaN
3   Neha  60000.0    Finance         5.0
4  Karan      NaN         IT         1.0

In [ ]:
df['Salary'].fillna(40000)

0    50000.0
1    40000.0
2    45000.0
3    60000.0
4    40000.0
Name: Salary, dtype: float64

In [ ]:
df

    Name   Salary Department  Experience
0   Aman  50000.0         IT         2.0
1   Riya      NaN         HR         3.0
2  Rahul  45000.0        NaN         NaN
3   Neha  60000.0    Finance         5.0
4  Karan      NaN         IT         1.0

In [ ]:
df['Department'].fillna('Unknown')

0         IT
1         HR
2    Unknown
3    Finance
4         IT
Name: Department, dtype: object

In [ ]:
df

    Name   Salary Department  Experience
0   Aman  50000.0         IT         2.0
1   Riya      NaN         HR         3.0
2  Rahul  45000.0        NaN         NaN
3   Neha  60000.0    Finance         5.0
4  Karan      NaN         IT         1.0

In [ ]:
df['Experience'].dropna( )

0    2.0
1    3.0
3    5.0
4    1.0
Name: Experience, dtype: float64

In [ ]:
df

    Name   Salary Department  Experience
0   Aman  50000.0         IT         2.0
1   Riya      NaN         HR         3.0
2  Rahul  45000.0        NaN         NaN
3   Neha  60000.0    Finance         5.0
4  Karan      NaN         IT         1.0

In [ ]:
# First DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Aman', 'Riya']
})

# Second DataFrame
df2 = pd.DataFrame({
    'ID': [3, 4],
    'Name': ['Rahul', 'Neha']
})
pd.concat([df1, df2])

   ID   Name
0   1   Aman
1   2   Riya
0   3  Rahul
1   4   Neha

In [ ]:

# First DataFrame
df1 = pd.DataFrame({
    'Name': ['Aman', 'Riya'],
    'Maths': [85, 92]
})

# Second DataFrame
df2 = pd.DataFrame({
    'Science': [88, 91]
})
pd.concat([df1, df2],axis=0)

   Name  Maths  Science
0  Aman   85.0      NaN
1  Riya   92.0      NaN
0   NaN    NaN     88.0
1   NaN    NaN     91.0

In [ ]:

# Students DataFrame
students = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Aman', 'Riya', 'Rahul']
})

# Marks DataFrame
marks = pd.DataFrame({
    'ID': [1, 2, 3],
    'Maths': [90, 85, 78]
})
pd.merge(students, marks, on='ID')

   ID   Name  Maths
0   1   Aman     90
1   2   Riya     85
2   3  Rahul     78

In [ ]:
# Students DataFrame
students = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Aman', 'Riya', 'Rahul']
})

# Marks DataFrame
marks = pd.DataFrame({
    'ID': [2, 3, 4],
    'Maths': [88, 76, 91]
})
pd.merge(students, marks, how='inner')

   ID   Name  Maths
0   2   Riya     88
1   3  Rahul     76

In [ ]:
pd.merge(students, marks, how='outer')

   ID   Name  Maths
0   1   Aman    NaN
1   2   Riya   88.0
2   3  Rahul   76.0
3   4    NaN   91.0

In [ ]:
pd.merge(students, marks, how='left')

   ID   Name  Maths
0   1   Aman    NaN
1   2   Riya   88.0
2   3  Rahul   76.0

In [ ]:
pd.merge(students, marks, how='right')

   ID   Name  Maths
0   2   Riya     88
1   3  Rahul     76
2   4    NaN     91

In [ ]:
# Student Info DataFrame
student_info = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Aman', 'Riya', 'Rahul']
})

# Marks DataFrame
marks = pd.DataFrame({
    'ID': [101, 102, 103],
    'Maths': [92, 81, 75]
})
df = student_info.join(marks.set_index('ID'), on='ID')
df

    ID   Name  Maths
0  101   Aman     92
1  102   Riya     81
2  103  Rahul     75

In [ ]:
# Students DataFrame
students = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Name': ['Aman', 'Riya', 'Rahul']
})

# Marks DataFrame
marks = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Maths': [85, 76, 90],
    'Science': [91, 88, 79]
})

# Attendance DataFrame
attendance = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Attendance': [95, 88, 97]
})

In [ ]:
df  = pd.merge(students, marks)

In [ ]:
pd.merge(df, attendance, on='StudentID')

   StudentID   Name  Maths  Science  Attendance
0          1   Aman     85       91          95
1          2   Riya     76       88          88
2          3  Rahul     90       79          97

In [ ]:
new_students = pd.DataFrame({
    "StudentID": [4, 5],
    "Name": ["Priya", "Arjun"]
})
students

   StudentID   Name
0          1   Aman
1          2   Riya
2          3  Rahul

In [ ]:
new_dff = pd.concat([students, new_students])
new_dff

   StudentID   Name
0          1   Aman
1          2   Riya
2          3  Rahul
0          4  Priya
1          5  Arjun

In [ ]:
students = students.set_index('StudentID')
attendance = attendance.set_index('StudentID')
result = students.join(attendance)

In [ ]:
result

            Name  Attendance
StudentID
1           Aman          95
2           Riya          88
3          Rahul          97

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Employee": ["Aman", "Riya", "Rahul", "Neha", "Karan"],
    "Salary": [50000, 45000, 60000, 48000, 55000]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary
0         IT     Aman   50000
1         HR     Riya   45000
2         IT    Rahul   60000
3         HR     Neha   48000
4    Finance    Karan   55000

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    55000.0
HR         46500.0
IT         55000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].agg(['sum','mean','max','min'])

               sum     mean    max    min
Department
Finance      55000  55000.0  55000  55000
HR           93000  46500.0  48000  45000
IT          110000  55000.0  60000  50000

In [ ]:
data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Delhi", "Indore"],
    "Name": ["Aman", "Riya", "Rahul", "Neha", "Karan"],
    "Age": [20, 22, 19, 23, 21]
}
df = pd.DataFrame(data)
df

     City   Name  Age
0  Bhopal   Aman   20
1  Indore   Riya   22
2  Bhopal  Rahul   19
3   Delhi   Neha   23
4  Indore  Karan   21

In [ ]:
df.groupby('City')['Age'].mean()

City
Bhopal    19.5
Delhi     23.0
Indore    21.5
Name: Age, dtype: float64

In [ ]:
df.groupby('City').size()

City
Bhopal    2
Delhi     1
Indore    2
dtype: int64

In [ ]:
data = {
    "Department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "Gender": ["Male", "Female", "Female", "Male", "Male", "Female"],
    "Salary": [50000, 55000, 45000, 48000, 60000, 62000]
}
df = pd.DataFrame(data)
df

  Department  Gender  Salary
0         IT    Male   50000
1         IT  Female   55000
2         HR  Female   45000
3         HR    Male   48000
4    Finance    Male   60000
5    Finance  Female   62000

In [ ]:
df.groupby(['Department', 'Gender'])['Salary'].mean()

Department  Gender
Finance     Female    62000.0
            Male      60000.0
HR          Female    45000.0
            Male      48000.0
IT          Female    55000.0
            Male      50000.0
Name: Salary, dtype: float64

In [ ]:
data = {
    "Class": ["A", "A", "B", "B", "A", "B"],
    "Student": ["Aman", "Riya", "Rahul", "Neha", "Karan", "Priya"],
    "Marks": [85, 78, 92, 88, 91, 75]
}
df = pd.DataFrame(data)
df

  Class Student  Marks
0     A    Aman     85
1     A    Riya     78
2     B   Rahul     92
3     B    Neha     88
4     A   Karan     91
5     B   Priya     75

In [ ]:
df.groupby('Class')['Marks'].mean()

Class
A    84.666667
B    85.000000
Name: Marks, dtype: float64

In [ ]:
df.groupby("Class")['Marks'].max()

Class
A    91
B    92
Name: Marks, dtype: int64

In [ ]:
df.groupby('Class')['Marks'].min()

Class
A    78
B    75
Name: Marks, dtype: int64

In [ ]:
df.groupby('Class')['Student'].size()

Class
A    3
B    3
Name: Student, dtype: int64

In [ ]:
data = {
    "Region": ["North", "South", "North", "South", "East", "East", "North", "South"],
    "Product": ["Laptop", "Laptop", "Mobile", "Mobile", "Laptop", "Mobile", "Laptop", "Mobile"],
    "Sales": [50000, 45000, 30000, 35000, 55000, 25000, 60000, 40000]
}
df = pd.DataFrame(data)
df

  Region Product  Sales
0  North  Laptop  50000
1  South  Laptop  45000
2  North  Mobile  30000
3  South  Mobile  35000
4   East  Laptop  55000
5   East  Mobile  25000
6  North  Laptop  60000
7  South  Mobile  40000

In [ ]:
df.groupby('Region')['Sales'].agg(['sum','mean'])

           sum          mean
Region
East     80000  40000.000000
North   140000  46666.666667
South   120000  40000.000000

In [ ]:
df.groupby('Product')['Sales'].agg(['min','max'])

           min    max
Product
Laptop   45000  60000
Mobile   25000  40000

In [ ]:
df.groupby(['Product', 'Region'])['Sales'].agg(['sum','size'])

                   sum  size
Product Region
Laptop  East     55000     1
        North   110000     2
        South    45000     1
Mobile  East     25000     1
        North    30000     1
        South    75000     2

In [ ]:
df.groupby(['Region'])['Sales'].max()

Region
East     55000
North    60000
South    45000
Name: Sales, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Employee": ["Aman","Riya","Rahul","Neha","Karan","Priya","Vivek","Anjali","Rohit","Sneha"],
    "Department": ["IT","HR","IT","Finance","HR","Finance","IT","HR","Finance","IT"],
    "City": ["Bhopal","Indore","Bhopal","Delhi","Delhi","Indore","Delhi","Bhopal","Indore","Delhi"],
    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"],
    "Salary": [50000,45000,60000,70000,48000,65000,55000,47000,72000,58000]
})
df

  Employee Department    City  Gender  Salary
0     Aman         IT  Bhopal    Male   50000
1     Riya         HR  Indore  Female   45000
2    Rahul         IT  Bhopal    Male   60000
3     Neha    Finance   Delhi  Female   70000
4    Karan         HR   Delhi    Male   48000
5    Priya    Finance  Indore  Female   65000
6    Vivek         IT   Delhi    Male   55000
7   Anjali         HR  Bhopal  Female   47000
8    Rohit    Finance  Indore    Male   72000
9    Sneha         IT   Delhi  Female   58000

In [ ]:
pd.pivot_table(df,values='Salary', index='Department')

                  Salary
Department
Finance     69000.000000
HR          46666.666667
IT          55750.000000

In [ ]:
df

  Employee Department    City  Gender  Salary
0     Aman         IT  Bhopal    Male   50000
1     Riya         HR  Indore  Female   45000
2    Rahul         IT  Bhopal    Male   60000
3     Neha    Finance   Delhi  Female   70000
4    Karan         HR   Delhi    Male   48000
5    Priya    Finance  Indore  Female   65000
6    Vivek         IT   Delhi    Male   55000
7   Anjali         HR  Bhopal  Female   47000
8    Rohit    Finance  Indore    Male   72000
9    Sneha         IT   Delhi  Female   58000

In [ ]:
pd.pivot_table(df, values='Salary', index='City', aggfunc='sum')

        Salary
City
Bhopal  157000
Delhi   231000
Indore  182000

In [ ]:
pd.pivot_table(df, values='Salary', index='Department', columns='Gender')

Gender       Female     Male
Department
Finance     67500.0  72000.0
HR          46000.0  48000.0
IT          58000.0  55000.0

In [ ]:
pd.pivot_table(df, values='Salary',index='City', columns='Department', aggfunc='max').fillna(0)

Department  Finance       HR       IT
City
Bhopal          0.0  47000.0  60000.0
Delhi       70000.0  48000.0  58000.0
Indore      72000.0  45000.0      0.0

In [ ]:
pd.crosstab(df['Department'], df['Gender'])

Gender      Female  Male
Department
Finance          2     1
HR               2     1
IT               1     3

In [ ]:
pd.pivot_table(df, values='Salary', index='City', columns ='Department')

Department  Finance       HR       IT
City
Bhopal          NaN  47000.0  55000.0
Delhi       70000.0  48000.0  56500.0
Indore      68500.0  45000.0      NaN

In [ ]:
pd.crosstab(df['City'], df['Gender'])

Gender  Female  Male
City
Bhopal       1     2
Delhi        2     2
Indore       2     1

In [ ]:
pd.pivot_table(df, values='Salary', index='City', columns ='Department', margins=True)

Department  Finance            HR       IT           All
City
Bhopal          NaN  47000.000000  55000.0  52333.333333
Delhi       70000.0  48000.000000  56500.0  57750.000000
Indore      68500.0  45000.000000      NaN  60666.666667
All         69000.0  46666.666667  55750.0  57000.000000

In [ ]:
pvt = pd.pivot_table(df, values='Salary', index='City', columns ='Department', margins = True)

In [ ]:
pvt = pvt.round(2)
pvt

Department  Finance        HR       IT       All
City
Bhopal          NaN  47000.00  55000.0  52333.33
Delhi       70000.0  48000.00  56500.0  57750.00
Indore      68500.0  45000.00      NaN  60666.67
All         69000.0  46666.67  55750.0  57000.00

# **Titanic Dataset**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('train.csv')
df_original = df.copy()

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.shape

(891, 12)

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [ ]:
age = df['Age'].median()
df['Age'] = df['Age'].fillna(age)

In [ ]:
df['Age'].isna().sum()

np.int64(0)

In [ ]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
df['Cabin'].isna().sum()

np.int64(687)

In [ ]:
# df.head()

In [ ]:
df_new = df.drop('Cabin', axis=1)

In [ ]:
df_new

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
df['HasCabin'] = df['Cabin'].notna().astype(int)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df['Family_size'] = df['SibSp'] +df['Parch'] +1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,HasCabin,Family_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1

In [ ]:
df['title'] = df['Name'].str.extract(r",\s*([^\.]+)\.")

In [ ]:
df['title'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'the Countess',
       'Jonkheer'], dtype=object)

In [ ]:
df['title'].value_counts()

title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [ ]:
title_count = df['title'].value_counts()
rare_title = title_count[title_count < 7].index
df['title'] = df['title'].replace(rare_title, "Rare")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,HasCabin,Family_size,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,2,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,2,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,2,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,1,Rare
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,1,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,0,4,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,1,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,1,Mr

In [ ]:
df['with family'] = (df['Family_size']>1).astype(int)

In [ ]:
df['Alone'] = (df['Family_size'] == 1).astype(int)

In [ ]:
df['Pass W/o Fam'] = df['Family_size']-1

In [ ]:
def fare_cat(fare):
  if fare > 20:
    return "High"
  elif (fare < 20) & (fare > 10):
    return "Mediun"
  elif fare <10:
    return "Low"
df['Fare Cat'] = df['Fare'].apply(fare_cat)

In [ ]:
df['High Fare'] = df['Fare'] > 20

In [ ]:
df['under_18'] = df['Age'] < 18

In [ ]:
df = df.drop(columns = 'Cabin')

In [ ]:
df.shape

(891, 20)

In [ ]:
print(f'old df : {df_original.shape} \n\nnew df : {df.shape}')

old df : (891, 12)

new df : (891, 20)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'HasCabin', 'Family_size',
       'title', 'with family', 'Alone', 'Pass W/o Fam', 'Fare Cat',
       'High Fare', 'under_18'],
      dtype='object')

In [ ]:
df = df.drop(columns=['Pass W/o Fam'])

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,HasCabin,Family_size,title,with family,Alone,Fare Cat,High Fare,under_18
0,1,0,3,male,22.0,1,0,7.2500,S,0,2,Mr,1,0,Low,False,False
1,2,1,1,female,38.0,1,0,71.2833,C,1,2,Mrs,1,0,High,True,False
2,3,1,3,female,26.0,0,0,7.9250,S,0,1,Miss,0,1,Low,False,False
3,4,1,1,female,35.0,1,0,53.1000,S,1,2,Mrs,1,0,High,True,False
4,5,0,3,male,35.0,0,0,8.0500,S,0,1,Mr,0,1,Low,False,False

In [ ]:
df_sorted = df.sort_values(by = 'Fare')

In [ ]:
df_sort_age = df.sort_values(by='Age', ascending=False)

In [ ]:
df_sort_two = df.sort_values(by=['Pclass', "Fare"])

In [ ]:
df.loc[df['Fare'].nlargest(10).index]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,HasCabin,Family_size,title,with family,Alone,Fare Cat,High Fare,under_18
258,259,1,1,female,35.0,0,0,512.3292,C,0,1,Miss,0,1,High,True,False
679,680,1,1,male,36.0,0,1,512.3292,C,1,2,Mr,1,0,High,True,False
737,738,1,1,male,35.0,0,0,512.3292,C,1,1,Mr,0,1,High,True,False
27,28,0,1,male,19.0,3,2,263.0000,S,1,6,Mr,1,0,High,True,False
88,89,1,1,female,23.0,3,2,263.0000,S,1,6,Miss,1,0,High,True,False
341,342,1,1,female,24.0,3,2,263.0000,S,1,6,Miss,1,0,High,True,False
438,439,0,1,male,64.0,1,4,263.0000,S,1,6,Mr,1,0,High,True,False
311,312,1,1,female,18.0,2,2,262.3750,C,1,5,Miss,1,0,High,True,False
742,743,1,1,female,21.0,2,2,262.3750,C,1,5,Miss,1,0,High,True,False
118,119,0,1,male,24.0,0,1,247.5208,C,1,2,Mr,1,0,High,True,False

In [ ]:
df.groupby('Pclass').size()

Pclass
1    216
2    184
3    491
dtype: int64

In [ ]:
df.groupby('Sex')['Age'].mean()

Sex
female    27.929936
male      30.140676
Name: Age, dtype: float64

In [ ]:
df.groupby('Pclass')['Fare'].sum()

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked', 'HasCabin', 'Family_size', 'title', 'with family',
       'Alone', 'Fare Cat', 'High Fare', 'under_18'],
      dtype='object')

In [ ]:
df.groupby('Sex')['Survived'].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [ ]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
df.groupby('Pclass')['Fare'].agg(['min','max','mean'])

        min       max       mean
Pclass
1       0.0  512.3292  84.154687
2       0.0   73.5000  20.662183
3       0.0   69.5500  13.675550

In [ ]:
df.groupby('Sex').agg({
    'Age': 'mean',
    'Fare':'mean',
    'Survived':'count'
})

              Age       Fare  Survived
Sex
female  27.929936  44.479818       314
male    30.140676  25.523893       577

In [ ]:
df.groupby(['Sex','Pclass'])['Survived'].count()

Sex     Pclass
female  1          94
        2          76
        3         144
male    1         122
        2         108
        3         347
Name: Survived, dtype: int64

In [ ]:
df.pivot_table(values='Survived', index='Sex', columns='Pclass', aggfunc = 'mean')

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
df.pivot_table(values='Fare', index='Embarked', columns= 'Pclass', aggfunc='mean')

Pclass             1          2          3
Embarked
C         104.718529  25.358335  11.214083
Q          90.000000  12.350000  11.183393
S          70.514244  20.327439  14.644083

In [ ]:
df.groupby('Embarked').agg({
    'Age' : 'mean',
    'Fare' : 'mean',
    'Survived' : 'sum'
})

                Age       Fare  Survived
Embarked
C         30.178095  59.954144        93
Q         28.032468  13.276030        30
S         29.307663  27.243651       219